baseProjectName: "gitops-kickstarter"
destination:
  server: https://kubernetes.default.svc
source:
  # When forked updated to your fork
  repoURL: https://github.com/kameshsampath/gitops-quickstart
  # the branch to use
  targetRevision: dev
sigstore:
  policyController: 
    version: 0.3.9
argocd:
  imageUpdater:
    version: 0.8.2
    logLevel: debug
helloWorld:
  deploy: true
  image:
    repo: docker.io/kameshsampath/go-hello-world:latest
