# the App of Apps project name where all core components will be deployed
baseProjectName: gitops-kickstarter
# The Kubernetes Cluster where the resources wil be created
# Defaults to local cluster where ArgoCD is deployed
destination:
  server: https://kubernetes.default.svc
# The Git Repository to used by the application for GitOps
source:
  # the source repository on git
  repoURL:
  # The branch/tag to use for the source repo
  targetRevision: main
# jetstack cert manager version
jetstack:
  certManager:
    version: v1.11.0
# the sigstore settings
sigstore:
  policyController:
    # policy controller helm chart version
    version: 0.3.9
# the argocd image updater
argocd:
  imageUpdater:
    image:
      # image updater tag to deploy 
      tag: v0.12.2
    # image updater helm chart version
    version: 0.8.2
    # image updater log level
    logLevel: debug
    # any container registries that need to be configured with image updater
    registries: []
# the hello world demo application
helloWorld:
  # flag to deploy hello world
  deploy: false
  image:
    # the container registry url to hello world application
    repo: ""
